// questions.js — Toàn bộ ngân hàng câu hỏi
// Thêm câu mới: copy 1 object, điền chapter/text/options/answer(index 0-3)/explanation
// chapter: 'C2' | 'C9' | 'C15' | 'C16' | 'C17' | 'C18' | 'C26'

const TOPICS = {
  'C2':  'C2 — Hệ thống tài chính',
  'C9':  'C9 — Ngân hàng & Quản trị',
  'C15': 'C15 — Cung tiền',
  'C16': 'C16 — Công cụ CSTT',
  'C17': 'C17 — Chiến lược CSTT',
  'C18': 'C18 — Tài chính quốc tế',
  'C26': 'C26 — Truyền dẫn CSTT',
};

const QUESTIONS = [
  // ── C2 ──────────────────────────────────────────────────────────────────
  {
    id: 1, chapter: 'C2',
    text: 'Thị trường tài chính SƠ CẤP khác thị trường THỨ CẤP ở chỗ:',
    options: [
      'Thị trường sơ cấp giao dịch chứng khoán đã phát hành; thứ cấp phát hành mới',
      'Thị trường sơ cấp phát hành chứng khoán MỚI (huy động vốn); thứ cấp giao dịch lại chứng khoán cũ',
      'Thị trường sơ cấp chỉ dành cho chính phủ; thứ cấp dành cho doanh nghiệp',
      'Thị trường sơ cấp có tính thanh khoản cao hơn',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Thị trường sơ cấp (primary market) là nơi phát hành chứng khoán lần đầu — IPO cổ phiếu, phát hành trái phiếu mới. Tiền từ nhà đầu tư chảy thẳng vào tổ chức phát hành để huy động vốn. Thị trường thứ cấp (secondary market) — NYSE, NASDAQ, HoSE — giao dịch lại chứng khoán đã phát hành; tổ chức phát hành KHÔNG nhận thêm tiền, nhưng thứ cấp quan trọng vì tạo thanh khoản, giúp nhà đầu tư sẵn sàng mua sơ cấp. 💡 Nhớ: sơ cấp = sinh ra; thứ cấp = mua bán lại. ❌ A: nói ngược lại. ❌ C: không có sự phân biệt chính phủ/DN. ❌ D: ngược lại — thứ cấp mới có thanh khoản cao.',
  },
  {
    id: 2, chapter: 'C2',
    text: 'Vấn đề "Adverse Selection" trong thị trường tài chính xảy ra KHI NÀO và có HỆ QUẢ gì?',
    options: [
      'Sau khi vay — người vay dùng tiền vào việc rủi ro hơn cam kết',
      'Trước khi vay — người có rủi ro cao có xu hướng tìm vay nhiều hơn → chất lượng bình quân người vay thấp',
      'Khi ngân hàng không giám sát đủ — người vay lười trả nợ',
      'Khi lãi suất tăng — người vay tốt rút lui khỏi thị trường',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Adverse selection là vấn đề thông tin bất cân xứng xảy ra TRƯỚC giao dịch (ex-ante). Người vay biết rõ rủi ro của mình, ngân hàng thì không. Khi lãi suất tăng, người vay "tốt" (dự án ổn định) rút khỏi thị trường vì chi phí vay cao hơn lợi tức kỳ vọng; người vay "xấu" (rủi ro cao, cần tiền gấp) vẫn chấp nhận vay → danh mục cho vay ngày càng xấu hơn — thị trường tín dụng có thể sụp đổ. 💡 Giải pháp: screening (sàng lọc), credit scoring, yêu cầu tài sản đảm bảo. ❌ A & C: đây là mô tả Moral Hazard (vấn đề SAU giao dịch). ❌ D: đây là hệ quả của adverse selection khi lãi suất tăng, không phải định nghĩa cốt lõi.',
  },
  {
    id: 3, chapter: 'C2',
    text: 'Tài trợ GIÁN TIẾP (indirect finance) khác tài trợ TRỰC TIẾP ở điểm nào?',
    options: [
      'Tài trợ gián tiếp nhanh hơn và rẻ hơn vì qua ít bước hơn',
      'Tài trợ gián tiếp đi qua trung gian tài chính (ngân hàng); trực tiếp: người tiết kiệm mua trực tiếp chứng khoán của người vay',
      'Tài trợ trực tiếp chỉ dành cho chính phủ',
      'Tài trợ gián tiếp chỉ xảy ra trên thị trường thứ cấp',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Tài trợ trực tiếp (direct finance): người tiết kiệm mua thẳng cổ phiếu/trái phiếu của doanh nghiệp trên thị trường vốn — đặc trưng của Mỹ và Anh. Tài trợ gián tiếp (indirect finance): tiền đi qua trung gian tài chính — ngân hàng nhận tiền gửi rồi cho vay — chiếm ưu thế ở hầu hết các nền kinh tế (Việt Nam, Nhật, Đức...). Tại sao gián tiếp phổ biến hơn? Vì trung gian tài chính có lợi thế trong xử lý thông tin bất cân xứng và giảm chi phí giao dịch nhờ kinh tế quy mô. ❌ A: gián tiếp không "nhanh hơn và rẻ hơn" — ưu thế của nó là xử lý bất cân xứng thông tin, không phải tốc độ. ❌ C & D: không có cơ sở trong lý thuyết.',
  },
  {
    id: 4, chapter: 'C2',
    text: 'Trung gian tài chính tồn tại chủ yếu vì 3 lý do. Lý do NÀO KHÔNG đúng?',
    options: [
      'Giảm chi phí giao dịch nhờ kinh tế quy mô',
      'Chia sẻ rủi ro qua đa dạng hóa danh mục',
      'Xử lý thông tin bất cân xứng tốt hơn cá nhân',
      'Đảm bảo lợi nhuận cao hơn đầu tư trực tiếp',
    ],
    answer: 3,
    explanation: '✅ Đúng (D — là lý do SAI): Ba lý do thực sự trung gian tài chính tồn tại theo Mishkin: (1) Giảm chi phí giao dịch nhờ kinh tế quy mô — ngân hàng xử lý hàng nghìn giao dịch, chi phí đơn vị thấp hơn cá nhân tự làm. (2) Chia sẻ rủi ro / asset transformation — ngân hàng chuyển hóa tài sản rủi ro (khoản vay DN) thành tiền gửi an toàn cho người gửi; đa dạng hóa danh mục làm giảm rủi ro tổng thể. (3) Giải quyết thông tin bất cân xứng — ngân hàng chuyên sàng lọc người vay (giảm adverse selection) và giám sát sau khi cho vay (giảm moral hazard). 💡 Không ai "đảm bảo" lợi nhuận cao hơn đầu tư trực tiếp — đây là điều không thể cam kết trong tài chính.',
  },
  {
    id: 5, chapter: 'C2',
    text: 'Moral Hazard trong quan hệ tín dụng là:',
    options: [
      'Ngân hàng cho vay lãi suất quá cao',
      'Người vay dùng tiền vào các hoạt động rủi ro hơn so với mục đích đã cam kết (SAU khi vay)',
      'Người vay giấu thông tin xấu trước khi vay',
      'Ngân hàng không đủ vốn để cho vay',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Moral Hazard là vấn đề thông tin bất cân xứng xảy ra SAU giao dịch (ex-post). Sau khi nhận tiền vay, người vay có thể đầu tư vào dự án rủi ro hơn cam kết — vì nếu thành công họ hưởng lợi lớn, nếu thất bại thì ngân hàng gánh phần lớn tổn thất (asymmetric payoff/lệch thưởng phạt). 💡 So sánh then chốt: Adverse selection = TRƯỚC vay (ai là người vay?), Moral hazard = SAU vay (người vay làm gì với tiền?). Giải pháp moral hazard: restrictive covenants (ràng buộc hành vi), monitoring (giám sát định kỳ), collateral (tài sản đảm bảo). ❌ C: "giấu thông tin xấu trước khi vay" là mô tả Adverse Selection, không phải Moral Hazard.',
  },

  // ── C9 ──────────────────────────────────────────────────────────────────
  {
    id: 6, chapter: 'C9',
    text: 'Ngân hàng "borrow short, lend long" chịu rủi ro gì?',
    options: [
      'Rủi ro tín dụng — khách hàng không trả được nợ',
      'Rủi ro lãi suất — lãi suất tăng làm tăng chi phí huy động trong khi thu nhập từ cho vay dài hạn cố định',
      'Rủi ro thị trường — giá cổ phiếu giảm',
      'Rủi ro pháp lý — vi phạm quy định',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Ngân hàng hoạt động theo mô hình "borrow short, lend long" — huy động tiền gửi ngắn hạn (lãi suất thả nổi, đáo hạn nhanh) rồi cho vay dài hạn (lãi suất cố định, đáo hạn lâu). Khi lãi suất thị trường tăng: chi phí huy động tăng ngay lập tức (phải trả lãi cao hơn cho người gửi), nhưng thu nhập từ khoản vay dài hạn lãi cố định không tăng → Net Interest Margin (NIM = lãi suất cho vay - lãi suất huy động) thu hẹp → lợi nhuận giảm, thậm chí thua lỗ. Đây chính là rủi ro lãi suất (interest rate risk). 💡 Bài học thực tế: Khủng hoảng Savings & Loan (S&L) Mỹ thập niên 1980 — hàng trăm tổ chức phá sản vì lãi suất tăng mạnh trong khi danh mục cho vay cố định dài hạn. ❌ A: Rủi ro tín dụng là khi khách hàng không trả được nợ — khác với rủi ro lãi suất. ❌ C & D: Không liên quan đến mô hình borrow short-lend long.',
  },
  {
    id: 7, chapter: 'C9',
    text: 'ROE = ROA × EM. NH A: ROA=1.5%, EM=10. NH B: ROA=0.8%, EM=18. Nhận xét nào ĐÚNG?',
    options: [
      'NH B tốt hơn vì ROE = 14.4% > NH A (15%) — sai, NH A ROE cao hơn',
      'NH A: ROE=15%, NH B: ROE=14.4% — NH A tốt hơn cả về lợi nhuận lẫn an toàn (EM thấp hơn)',
      'ROE bằng nhau nên hai NH tương đương',
      'NH B an toàn hơn vì EM cao hơn',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Tính toán: NH A: ROE = ROA × EM = 1.5% × 10 = 15%. NH B: ROE = 0.8% × 18 = 14.4%. 💡 Hiểu công thức: ROA (Return on Assets) = Lợi nhuận ròng / Tổng tài sản — đo hiệu quả sử dụng tài sản. EM (Equity Multiplier) = Tổng tài sản / Vốn CSH — đo mức độ đòn bẩy tài chính. ROE = ROA × EM: ngân hàng có thể tăng ROE bằng cách tăng đòn bẩy (EM), nhưng đây là con dao hai lưỡi — EM cao nghĩa là vốn CSH mỏng, rủi ro phá sản cao hơn khi tài sản mất giá. NH A vừa ROE cao hơn (15% > 14.4%), vừa an toàn hơn (EM thấp hơn: 10 vs 18). NH B phải "đánh đổi" an toàn để đạt ROE xấp xỉ NH A. ❌ D: EM cao = kém an toàn hơn, không phải ngược lại.',
  },
  {
    id: 8, chapter: 'C9',
    text: 'Ngân hàng thiếu hụt thanh khoản đột ngột. Cách nào CÓ CHI PHÍ CAO NHẤT?',
    options: [
      'Vay Fed funds từ ngân hàng khác',
      'Bán chứng khoán có sẵn',
      'Vay chiết khấu tại Fed (discount window)',
      'Thu hồi hoặc bán các khoản cho vay',
    ],
    answer: 3,
    explanation: '✅ Đúng (D): Khi thiếu thanh khoản đột ngột, ngân hàng có nhiều lựa chọn — xếp từ rẻ đến đắt: (1) Vay Fed funds (liên ngân hàng): nhanh, lãi suất thị trường, không cần thế chấp — rẻ nhất. (2) Bán chứng khoán: thanh khoản khá cao, mất thu nhập lãi nhưng không mất quan hệ khách hàng. (3) Vay chiết khấu Fed (discount window): có "stigma" (thị trường nghi ngờ ngân hàng đang gặp khó), nhưng chi phí tài chính vẫn thấp hơn bán cho vay. (4) Thu hồi/bán khoản cho vay: tốn kém nhất — phải bán với chiết khấu lớn (thị trường kém thanh khoản cho loại tài sản này), mất quan hệ khách hàng dài hạn, mất toàn bộ dòng thu nhập lãi tương lai. 💡 Bài học: ngân hàng quản lý thanh khoản tốt sẽ duy trì "liquidity buffer" (tiền mặt + chứng khoán có thể bán nhanh) để tránh phải bán cho vay trong tình huống khủng hoảng.',
  },
  {
    id: 9, chapter: 'C9',
    text: 'Yêu cầu vốn tối thiểu (capital requirements) theo Basel được thiết kế để:',
    options: [
      'Tăng lợi nhuận cho ngân hàng',
      'Giảm chi phí huy động vốn',
      'Đảm bảo ngân hàng có đủ "bộ đệm" hấp thụ tổn thất, bảo vệ người gửi tiền',
      'Cho phép ngân hàng tăng đòn bẩy tối đa',
    ],
    answer: 2,
    explanation: '✅ Đúng (C): Yêu cầu vốn tối thiểu (capital adequacy requirements) theo Basel buộc ngân hàng phải duy trì tỷ lệ vốn chủ sở hữu tối thiểu so với tài sản có trọng số rủi ro (risk-weighted assets). Mục đích cốt lõi: vốn CSH đóng vai trò "bộ đệm" (buffer) — khi tài sản mất giá hoặc có tổn thất tín dụng, vốn CSH hấp thụ trước, bảo vệ người gửi tiền và hệ thống tài chính. 💡 Trade-off quan trọng: vốn cao hơn → an toàn hơn, nhưng EM giảm → ROE giảm (ROE = ROA × EM). Vì vậy, ngân hàng có động cơ tối thiểu hóa vốn CSH và tìm cách lách quy định (regulatory arbitrage) — ví dụ chuyển tài sản ra ngoại bảng để giảm risk-weighted assets. Basel III (sau 2008) siết chặt hơn Basel II nhằm vá lỗ hổng này. ❌ A & B: Vốn yêu cầu thường làm giảm lợi nhuận và tăng chi phí huy động. ❌ D: Ngược lại — yêu cầu vốn giới hạn đòn bẩy, không cho phép tăng tối đa.',
  },
  {
    id: 10, chapter: 'C9',
    text: 'Hoạt động ngoại bảng (off-balance-sheet) nào tạo ra rủi ro TIỀM ẨN lớn nhất?',
    options: [
      'Cho thuê tài chính',
      'Giao dịch phái sinh (derivatives) để đầu cơ',
      'Dịch vụ thanh toán',
      'Tư vấn tài chính',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Hoạt động ngoại bảng (off-balance-sheet) là những cam kết/rủi ro KHÔNG xuất hiện trực tiếp trên bảng cân đối kế toán, nhưng có thể gây tổn thất thực sự rất lớn. Giao dịch phái sinh (derivatives) để đầu cơ nguy hiểm nhất vì: đòn bẩy cực cao (kiểm soát giá trị hợp đồng lớn với vốn ban đầu nhỏ), tổn thất tiềm năng không có giới hạn (đặc biệt với options bán khống, futures), và biến động giá tài sản cơ sở có thể khuếch đại lỗ theo hệ số hàng chục lần. 💡 Bài học thực tế: Barings Bank (1995) — Nick Leeson thua lỗ 1.3 tỷ USD từ futures, phá sản ngân hàng 233 tuổi. Société Générale (2008) — Jérôme Kerviel lỗ 4.9 tỷ EUR từ futures. AIG (2008) — phái sinh credit default swaps gây khủng hoảng tài chính toàn cầu. ❌ A: Cho thuê tài chính thường có tài sản đảm bảo rõ ràng. ❌ C & D: Dịch vụ thanh toán và tư vấn tạo phí, rủi ro tương đối thấp.',
  },

  // ── C15 ─────────────────────────────────────────────────────────────────
  {
    id: 11, chapter: 'C15',
    text: 'Với c=0.2, rr=0.1, e=0.05, số nhân tiền m bằng bao nhiêu?',
    options: ['m = 10 (1/rr)', 'm = 5', 'm ≈ 3.43', 'm ≈ 2.0'],
    answer: 2,
    explanation: '✅ Đúng (C): Công thức số nhân tiền đầy đủ: m = (1+c)/(rr+e+c), trong đó c = tỷ lệ tiền mặt/tiền gửi (công chúng quyết định), rr = tỷ lệ dự trữ bắt buộc (Fed quyết định), e = tỷ lệ dự trữ vượt mức/tiền gửi (ngân hàng quyết định). Tính: m = (1+0.2)/(0.1+0.05+0.2) = 1.2/0.35 ≈ 3.43. 💡 So sánh với số nhân đơn giản: m = 1/rr = 1/0.1 = 10 — gấp gần 3 lần! Số nhân đơn giản giả định không ai giữ tiền mặt (c=0) và ngân hàng không giữ dự trữ vượt mức (e=0) — không thực tế. c và e "rò rỉ" tiền ra khỏi chu trình nhân tiền, làm số nhân giảm mạnh. ❌ A: 1/rr=10 chỉ đúng trong mô hình lý tưởng. ❌ B & D: không khớp với công thức.',
  },
  {
    id: 12, chapter: 'C15',
    text: 'Người dân rút $100 triệu tiền mặt từ ngân hàng. Tác động lên MB và M là:',
    options: [
      'MB giảm $100M; M giảm nhiều hơn $100M',
      'MB không đổi; M giảm (vì c↑ → m↓)',
      'MB tăng; M không đổi',
      'MB giảm $100M; M giảm đúng $100M',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Đây là bẫy tư duy kinh điển — cần phân biệt rõ MB và M. MB (Monetary Base / tiền cơ sở) = C (tiền mặt lưu hành) + R (dự trữ ngân hàng). Khi người dân rút 100M mặt từ ngân hàng: C tăng 100M, R giảm 100M → MB = C + R KHÔNG ĐỔI (hai chiều triệt tiêu nhau). NHƯNG: c = C/D tăng (nhiều tiền mặt hơn so với tiền gửi) → số nhân m = (1+c)/(rr+e+c) giảm → M = m × MB giảm, dù MB không đổi. 💡 Kết luận: cùng một lượng MB nhưng nếu c cao (dân ưa giữ tiền mặt), cung tiền M sẽ thấp hơn. Đây là lý do hành vi công chúng ảnh hưởng đến cung tiền dù Fed không thay đổi chính sách. ❌ A: MB không thay đổi (không phải giảm). ❌ C: MB không tăng. ❌ D: M giảm nhiều hơn 100M do hiệu ứng số nhân.',
  },
  {
    id: 13, chapter: 'C15',
    text: 'Khủng hoảng 1929-1933: Fed tăng MB nhưng M vẫn giảm 1/3. Giải thích tốt nhất:',
    options: [
      'Fed không thực sự tăng MB',
      'Tăng rr làm m giảm nhiều hơn MB tăng',
      'c tăng (dân hoảng loạn rút tiền mặt) VÀ e tăng (NH sợ mất thanh khoản giữ ER) → m giảm mạnh hơn MB tăng',
      'Fed sai lầm giảm MB thay vì tăng',
    ],
    answer: 2,
    explanation: '✅ Đúng (C): Đây là bài học lịch sử quan trọng nhất về CSTT. Khủng hoảng 1929-33: hàng nghìn ngân hàng phá sản, người dân hoảng loạn rút tiền mặt (bank runs) → c tăng vọt. Các ngân hàng còn sống sợ mất thanh khoản → tích trữ dự trữ vượt mức → e tăng mạnh. Hệ quả: m = (1+c)/(rr+e+c) giảm cực mạnh vì cả tử số nhỏ hơn lẫn mẫu số lớn hơn. Dù Fed có tăng MB, M = m × MB vẫn giảm 1/3 vì m giảm nhanh hơn tốc độ bơm MB. 💡 Milton Friedman & Anna Schwartz trong "A Monetary History of the United States" (1963) gọi đây là "Great Contraction" — sai lầm CSTT nghiêm trọng nhất lịch sử Mỹ. Fed đã để cung tiền sụp đổ thay vì bơm đủ để bù đắp. Bài học này định hình phản ứng của Bernanke (Fed) năm 2008 — bơm tiền mạnh tay để ngăn deflation. ❌ B: rr là công cụ Fed kiểm soát, không tự thay đổi gây ra khủng hoảng. ❌ A & D: không đúng với sự kiện lịch sử.',
  },
  {
    id: 14, chapter: 'C15',
    text: 'Ai trong 3 chủ thể có ảnh hưởng TRỰC TIẾP nhất đến MB?',
    options: [
      'Ngân hàng thương mại (qua quyết định dự trữ)',
      'Công chúng (qua tỷ lệ nắm giữ tiền mặt)',
      'Fed (NHTW) qua OMO và cho vay chiết khấu',
      'Bộ Tài chính qua thu chi ngân sách',
    ],
    answer: 2,
    explanation: '✅ Đúng (C): Trong mô hình 3 chủ thể của Mishkin, mỗi bên kiểm soát một phần khác nhau: Fed (NHTW) kiểm soát TRỰC TIẾP MB = C + R qua: (1) OMO (Open Market Operations) — mua/bán trái phiếu CP, công cụ chủ lực và linh hoạt nhất; (2) Discount lending — cho ngân hàng vay qua discount window, ảnh hưởng đến BR. Ngân hàng thương mại quyết định e (tỷ lệ dự trữ vượt mức) — ảnh hưởng GIÁN TIẾP đến số nhân m. Công chúng quyết định c (tỷ lệ tiền mặt/tiền gửi) — ảnh hưởng GIÁN TIẾP đến m. 💡 Vì NH TM và công chúng cùng ảnh hưởng đến m, Fed không kiểm soát hoàn toàn M = m × MB — đây là lý do CSTT đôi khi có kết quả ngoài dự kiến. ❌ D: Bộ Tài chính ảnh hưởng gián tiếp qua thâm hụt ngân sách và phát hành trái phiếu, không kiểm soát MB trực tiếp.',
  },
  {
    id: 15, chapter: 'C15',
    text: 'Fed bơm $200 tỷ qua OMO mua, với c=0.3, rr=0.1, e=0.05. Cung tiền M tăng xấp xỉ bao nhiêu?',
    options: ['$200 tỷ', '$2,000 tỷ (1/rr × MB)', '≈ $578 tỷ', '≈ $1,400 tỷ'],
    answer: 2,
    explanation: '✅ Đúng (C): Từng bước tính: Bước 1 — tính số nhân m: m = (1+c)/(rr+e+c) = (1+0.3)/(0.1+0.05+0.3) = 1.3/0.45 ≈ 2.89. Bước 2 — tính ΔM: ΔM = m × ΔMB = 2.89 × 200 tỷ ≈ 578 tỷ. 💡 So sánh các đáp án: 200 tỷ (A) = chỉ tính MB tăng, bỏ qua hiệu ứng nhân — sai. 2,000 tỷ (B) = dùng 1/rr = 10, bỏ qua c và e — quá lạc quan, không thực tế. 578 tỷ (C) = đúng, dùng công thức đầy đủ. 1,400 tỷ (D) = không khớp bất kỳ công thức nào. Lưu ý: OMO mua → Fed trả tiền bằng cách tăng dự trữ ngân hàng (NBR tăng) → MB tăng 200 tỷ → cung tiền tăng theo số nhân.',
  },

  // ── C16 ─────────────────────────────────────────────────────────────────
  {
    id: 16, chapter: 'C16',
    text: 'Fed giảm lãi suất chiết khấu nhưng KHÔNG có ngân hàng nào đang vay chiết khấu (BR=0). Lãi suất liên ngân hàng (iff) sẽ:',
    options: [
      'Giảm ngay lập tức',
      'Tăng vì ngân hàng cần bù đắp chi phí',
      'Không đổi — trần lãi suất hạ xuống nhưng không ràng buộc điểm cân bằng',
      'Giảm sau độ trễ 3-6 tháng',
    ],
    answer: 2,
    explanation: '✅ Đúng (C): Để hiểu câu này cần nắm mô hình thị trường dự trữ (reserve market). Đường cung dự trữ (Rs) có hình chữ L ngược: đoạn nằm ngang phía trên = lãi suất chiết khấu (discount rate) — là TRẦN, khi iff chạm trần NH sẽ vay discount window thay vì trả cao hơn. Đoạn thẳng đứng = tại mức NBR (khi BR=0, toàn bộ dự trữ là NBR). Khi BR=0: điểm cân bằng iff nằm trên đoạn THẲNG ĐỨNG — tức Rs và Rd cắt nhau ở đoạn không phụ thuộc discount rate. Giảm discount rate chỉ dịch chuyển PHẦN NẰM NGANG xuống thấp hơn — nhưng không ảnh hưởng điểm cân bằng vì điểm cân bằng không nằm ở đó. 💡 Bài học: discount rate chỉ có tác dụng khi iff đang bằng discount rate (BR > 0). Nếu không có ngân hàng nào vay, công cụ này "vô hiệu" với iff. ❌ A: iff không giảm vì điểm cân bằng không thay đổi. ❌ D: không có độ trễ — vấn đề là công cụ này không có tác dụng trong tình huống BR=0.',
  },
  {
    id: 17, chapter: 'C16',
    text: 'OMO (nghiệp vụ thị trường mở) được coi là công cụ tốt nhất vì:',
    options: [
      'Tác động mạnh nhất đến nền kinh tế',
      'Fed kiểm soát 100%, linh hoạt, có thể đảo ngược nhanh, tác động ngay lên dự trữ NH',
      'Không cần sự chấp thuận của Quốc hội',
      'Không gây lạm phát',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): OMO vượt trội so với 2 công cụ còn lại nhờ 4 đặc tính: (1) Fed hoàn toàn chủ động — không phụ thuộc vào ngân hàng có muốn vay hay không (khác discount window). (2) Linh hoạt về quy mô — từ vài triệu đến hàng tỷ, điều chỉnh từng bước nhỏ. (3) Dễ đảo ngược — nếu bơm quá nhiều, bán lại ngay; nếu hút quá, mua lại. (4) Tác động tức thì — ngay khi giao dịch, NBR thay đổi → iff thay đổi. 💡 So sánh với 2 công cụ còn lại: Discount rate — phụ thuộc ngân hàng có chủ động vay không (thụ động); thay đổi mang tính "tín hiệu" nhiều hơn là kiểm soát trực tiếp. Dự trữ bắt buộc (RR) — kém linh hoạt, không thể điều chỉnh hàng ngày, thay đổi nhỏ gây biến động lớn, gây bất ổn cho kế hoạch kinh doanh của ngân hàng. ❌ A: "tác động mạnh nhất" không phải tiêu chí — RR có tác động mạnh hơn nhưng kém linh hoạt.',
  },
  {
    id: 18, chapter: 'C16',
    text: 'Quantitative Easing (QE) khác OMO thông thường ở điểm chính nào?',
    options: [
      'QE chỉ dành cho thời bình, OMO cho khủng hoảng',
      'QE mua CK ngắn hạn; OMO mua CK dài hạn',
      'QE mua tài sản quy mô lớn gồm CK DÀI HẠN và MBS khi iff ≈ 0 (ZLB); OMO thông thường mua CK ngắn hạn',
      'QE do Bộ Tài chính thực hiện, OMO do Fed',
    ],
    answer: 2,
    explanation: '✅ Đúng (C): OMO thông thường vs QE — khác nhau về mục tiêu, tài sản, và bối cảnh: OMO thông thường: mua/bán T-Bills (ngắn hạn <1 năm), quy mô vừa phải, mục tiêu điều chỉnh iff (lãi suất ngắn hạn). QE (Quantitative Easing): triển khai khi iff đã về 0 (Zero Lower Bound — ZLB), không thể giảm thêm. Fed chuyển sang mua tài sản dài hạn: Treasury 10-30 năm, MBS (Mortgage-Backed Securities). Mục tiêu: kéo giảm lãi suất DÀI HẠN để kích thích đầu tư bất động sản, vay doanh nghiệp. Quy mô khổng lồ: QE1 (2008-2010) = 1.7 nghìn tỷ USD; QE2 (2010-2011) = 600 tỷ; QE3 (2012-2014) = 85 tỷ/tháng. 💡 QE là "unconventional monetary policy" — công cụ phi truyền thống khi kho vũ khí thông thường cạn kiệt. ❌ A & B: nói ngược hoàn toàn. ❌ D: QE do Fed thực hiện, không phải Bộ Tài chính.',
  },
  {
    id: 19, chapter: 'C16',
    text: 'Tăng tỷ lệ dự trữ bắt buộc (rr) có tác động KÉP là:',
    options: [
      'Chỉ tăng iff, không ảnh hưởng M',
      'Giảm iff và tăng M',
      'Tăng iff (Rd dịch phải) VÀ giảm M (m giảm) — thắt chặt kép',
      'Tăng iff nhưng tăng M vì NH vay thêm từ Fed',
    ],
    answer: 2,
    explanation: '✅ Đúng (C): Tăng tỷ lệ dự trữ bắt buộc (rr) gây ra 2 tác động đồng thời — cả hai đều thắt chặt tiền tệ: Tác động 1 — Thị trường dự trữ: rr↑ → ngân hàng phải giữ nhiều dự trữ bắt buộc hơn trên cùng lượng tiền gửi → cầu dự trữ (Rd) tăng, dịch PHẢI → tại cùng mức cung, iff tăng → chi phí vay liên ngân hàng cao hơn → tín dụng thu hẹp. Tác động 2 — Số nhân tiền: m = (1+c)/(rr+e+c), rr↑ → mẫu số tăng → m giảm → M = m × MB giảm (dù MB không đổi). 💡 Đây là "tác động kép thắt chặt" — vừa tăng lãi suất ngắn hạn, vừa trực tiếp thu hẹp cung tiền. Chính vì hiệu lực quá mạnh và lan rộng, RR là công cụ ít được dùng — thay đổi nhỏ gây biến động lớn, khó hiệu chỉnh. ❌ A: RR ảnh hưởng cả iff lẫn M. ❌ B: RR tăng thì iff tăng (không giảm) và M giảm (không tăng).',
  },
  {
    id: 20, chapter: 'C16',
    text: 'IOR (Interest on Reserves) đóng vai trò gì trên thị trường dự trữ?',
    options: [
      'Trần (ceiling) của iff',
      'Sàn (floor) của iff — iff không thể giảm xuống dưới IOR',
      'Mức cân bằng của iff',
      'Không ảnh hưởng iff vì IOR là lãi suất nội bộ của Fed',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): IOR (Interest on Reserves) là lãi suất Fed trả cho phần dự trữ ngân hàng gửi tại Fed (bao gồm cả dự trữ vượt mức từ 2008). Logic của sàn lãi suất: nếu iff < IOR, ngân hàng sẽ từ chối cho vay trên thị trường liên ngân hàng và chuyển tiền vào Fed để hưởng IOR rủi ro thấp hơn → cung dự trữ trên thị trường liên NH giảm → iff bị đẩy lên không thể xuống dưới IOR. Vì vậy IOR = SÀN (floor) của iff. 💡 Ý nghĩa thực tiễn: Trước 2008, Fed không trả IOR → "corridor system" (iff dao động giữa discount rate và 0). Sau 2008, Fed bắt đầu trả IOR → chuyển sang "floor system": tăng IOR = tăng iff, giảm IOR = giảm iff. Đây là công cụ kiểm soát lãi suất chính sách hiện đại, đặc biệt hữu ích khi hệ thống tràn ngập dự trữ sau QE. ❌ A: Trần là discount rate (lãi suất chiết khấu), không phải IOR. ❌ C: IOR là sàn, không phải điểm cân bằng.',
  },

  // ── C17 ─────────────────────────────────────────────────────────────────
  {
    id: 21, chapter: 'C17',
    text: 'Vấn đề "time-inconsistency" của NHTW là gì?',
    options: [
      'NHTW thay đổi mục tiêu quá thường xuyên',
      'NHTW có động cơ mở rộng tiền tệ bất ngờ sau khi đã hứa giữ lạm phát thấp — phá vỡ cam kết để đạt lợi ích ngắn hạn',
      'NHTW không thể dự báo lạm phát chính xác',
      'NHTW mất quá nhiều thời gian ra quyết định',
    ],
    answer: 1,
    explanation: 'Time-inconsistency: NHTW hứa LP thấp → kỳ vọng LP thấp → Sau đó bị cám dỗ mở rộng tiền tệ (để Y↑ ngắn hạn) → LP tăng → mất uy tín. Giải pháp: Neo danh nghĩa + Độc lập NHTW + Minh bạch/trách nhiệm giải trình.',
  },
  {
    id: 22, chapter: 'C17',
    text: 'Lạm phát mục tiêu (Inflation Targeting) KHÔNG bao gồm yếu tố nào?',
    options: [
      'Công bố mục tiêu LP số cụ thể (VD: 2% ± 1%)',
      'Cam kết ổn định giá là ưu tiên hàng đầu',
      'Sử dụng DUY NHẤT M2 làm chỉ báo trung gian',
      'Minh bạch thông qua báo cáo lạm phát định kỳ',
    ],
    answer: 2,
    explanation: '5 yếu tố của IT: (1) Công bố mục tiêu LP số cụ thể; (2) Ổn định giá là ưu tiên; (3) Sử dụng NHIỀU chỉ số thông tin (không chỉ M2 — vì mối quan hệ M-LP không ổn định); (4) Minh bạch; (5) Trách nhiệm giải trình. Đáp án C SAI.',
  },
  {
    id: 23, chapter: 'C17',
    text: 'Taylor Rule: π=4%, π*=2%, r*=2%, output gap=+2%. Lãi suất mục tiêu i_ff là:',
    options: ['6%', '7%', '8%', '9%'],
    answer: 2,
    explanation: 'i_ff = π + r* + 0.5(π−π*) + 0.5(gap) = 4 + 2 + 0.5(4−2) + 0.5(2) = 4+2+1+1 = 8%. LP vượt mục tiêu 2pp → +1pp; Sản lượng vượt tiềm năng 2% → +1pp.',
  },
  {
    id: 24, chapter: 'C17',
    text: '"Hierarchical mandate" của ECB khác "dual mandate" của Fed ở điểm cốt lõi nào?',
    options: [
      'ECB có thể in tiền nhiều hơn Fed',
      'Fed ưu tiên ổn định giá tuyệt đối; ECB cân bằng LP và việc làm',
      'ECB coi ổn định giá là ưu tiên TUYỆT ĐỐI; Fed cân bằng cả LP lẫn việc làm (ngang nhau)',
      'Cả hai đều có mandate như nhau, chỉ khác tên gọi',
    ],
    answer: 2,
    explanation: 'ECB (Hierarchical): ổn định giá > tất cả → chậm nới lỏng khi suy thoái nếu LP chưa về mục tiêu. Fed (Dual): LP và việc làm ngang nhau → nới lỏng mạnh hơn/sớm hơn khi thất nghiệp tăng. Bằng chứng: 2008-2009, Fed cắt lãi suất nhanh và mạnh hơn ECB nhiều.',
  },
  {
    id: 25, chapter: 'C17',
    text: 'Lạm phát tăng 1pp theo Taylor Rule, lãi suất danh nghĩa cần tăng bao nhiêu để CSTT đủ thắt chặt?',
    options: [
      'Tăng 0.5pp',
      'Tăng đúng 1pp (lãi suất thực không đổi)',
      'Tăng 1.5pp (lãi suất thực tăng 0.5pp) — "Taylor Principle"',
      'Tăng 2pp',
    ],
    answer: 2,
    explanation: '"Taylor Principle": khi LP tăng 1pp, i_ff phải tăng 1.5pp (1pp từ hạng π + 0.5pp từ hạng 0.5×(π−π*)) → lãi suất thực r = i − π tăng 0.5pp. NẾU i chỉ tăng 1pp → r không đổi → CSTT không đủ thắt chặt → LP không kiềm được.',
  },

  // ── C18 ─────────────────────────────────────────────────────────────────
  {
    id: 26, chapter: 'C18',
    text: 'Can thiệp ngoại hối CÓ VÔ HIỆU HÓA (sterilized) khác KHÔNG VÔ HIỆU HÓA (unsterilized) như thế nào?',
    options: [
      'Sterilized nhanh hơn về tác động lên tỷ giá',
      'Unsterilized: can thiệp + OMO bù đắp → MB không đổi; Sterilized: can thiệp không kèm OMO → MB thay đổi',
      'Cả hai đều không ảnh hưởng MB',
      'Unsterilized: MB thay đổi → M thay đổi → tác động MẠNH; Sterilized: MB không đổi → tác động YẾU',
    ],
    answer: 3,
    explanation: 'Unsterilized = không bù đắp → MB thay đổi → M thay đổi → tác động MẠNH lên tỷ giá và kinh tế. Sterilized = kèm OMO bù đắp → MB không đổi → M không đổi → tác động YẾU (chỉ qua kênh trực tiếp, ngắn hạn).',
  },
  {
    id: 27, chapter: 'C18',
    text: 'Bộ ba bất khả thi (Impossible Trinity): một quốc gia KHÔNG THỂ đồng thời có:',
    options: [
      'Lạm phát thấp, tăng trưởng cao và thất nghiệp thấp',
      'Tỷ giá cố định, tự do dòng vốn và CSTT độc lập',
      'Tăng trưởng xuất khẩu, nhập khẩu thấp và dự trữ ngoại hối lớn',
      'Độc lập tài khóa, độc lập tiền tệ và thặng dư ngân sách',
    ],
    answer: 1,
    explanation: 'Mundell-Fleming Impossible Trinity: (1) Tỷ giá cố định, (2) Tự do dòng vốn, (3) CSTT độc lập. Chỉ chọn được 2/3. HK=(1)+(2); TQ=(1)+(3) kiểm soát vốn; Mỹ=(2)+(3) tỷ giá thả nổi.',
  },
  {
    id: 28, chapter: 'C18',
    text: 'Thâm hụt tài khoản vãng lai (CA < 0). Theo đồng nhất thức BOP, điều gì PHẢI xảy ra?',
    options: [
      'Dự trữ ngoại hối tăng tự động',
      'Tài khoản tài chính FA > 0 (nhập ròng vốn — vốn từ nước ngoài vào)',
      'Đồng nội tệ phải phá giá ngay lập tức',
      'Cung tiền nội địa giảm tự động',
    ],
    answer: 1,
    explanation: 'CA + FA = 0. CA < 0 → FA phải > 0 (nhập ròng vốn). Nhập khẩu > xuất khẩu → cần vốn nước ngoài vào để tài trợ. Mỹ: thâm hụt CA lớn → FA > 0 (TQ, Nhật mua trái phiếu Mỹ). Nếu FA không đủ → dự trữ ngoại hối giảm.',
  },
  {
    id: 29, chapter: 'C18',
    text: 'Tỷ giá mục tiêu (exchange rate targeting) có nhược điểm LỚN NHẤT là:',
    options: [
      'Quá phức tạp để thực hiện',
      'Mất CSTT độc lập — phải đi theo CSTT của nước neo',
      'Gây lạm phát cao',
      'Làm tăng thất nghiệp',
    ],
    answer: 1,
    explanation: 'Khi neo tỷ giá vào USD: nước neo PHẢI giữ lãi suất tương đương Mỹ để tránh dòng vốn rời đi. Mỹ tăng lãi suất → nước neo phải tăng theo (dù kinh tế không cần) → mất tự chủ CSTT. Thêm: dễ bị tấn công đầu cơ (bài học: Thái Lan 1997, Anh 1992).',
  },
  {
    id: 30, chapter: 'C18',
    text: 'Đồng USD tăng giá mạnh so với EUR. Tác động lên nền kinh tế Mỹ:',
    options: [
      'Xuất khẩu Mỹ tăng; nhập khẩu vào Mỹ giảm',
      'Xuất khẩu Mỹ giảm (đắt hơn tương đối); nhập khẩu vào Mỹ tăng (rẻ hơn) → NX↓ → Y↓',
      'Không ảnh hưởng vì Mỹ có thị trường nội địa lớn',
      'Lạm phát Mỹ tăng vì hàng nhập khẩu đắt hơn',
    ],
    answer: 1,
    explanation: 'USD mạnh: hàng Mỹ đắt hơn với người nước ngoài → XK↓; hàng nước ngoài rẻ hơn với người Mỹ → NK↑ → NX↓ → Y↓. Thêm: nhập khẩu rẻ → lạm phát Mỹ có xu hướng↓ (không phải tăng).',
  },

  // ── C26 ─────────────────────────────────────────────────────────────────
  {
    id: 31, chapter: 'C26',
    text: 'CSTT mở rộng (M ↑). Chuỗi tác động qua kênh TỶ GIÁ đến Y là:',
    options: [
      'M↑ → i↑ → Vốn vào → Nội tệ mạnh → NX↑ → Y↑',
      'M↑ → i↓ → Vốn ra → Nội tệ yếu (E↑) → Xuất khẩu rẻ hơn → NX↑ → Y↑',
      'M↑ → i↓ → Tỷ giá không đổi → NX không đổi',
      'M↑ → Tỷ giá tăng → Nhập khẩu rẻ hơn → C↑ → Y↑',
    ],
    answer: 1,
    explanation: 'Kênh tỷ giá: M↑ → i↓ → tài sản nội địa kém hấp dẫn → vốn chảy ra → nội tệ mất giá (E↑) → hàng xuất khẩu rẻ hơn tương đối → XK↑, NK↓ → NX↑ → Y↑. Quan trọng với nền kinh tế mở nhỏ (VN, Singapore).',
  },
  {
    id: 32, chapter: 'C26',
    text: "Tobin's q = 0.7. Điều này hàm ý doanh nghiệp nên:",
    options: [
      'Đầu tư mới vì cổ phiếu đang đắt',
      'Mua lại doanh nghiệp hiện có vì rẻ hơn xây mới — I mới không có lợi',
      'Phát hành thêm cổ phiếu để huy động vốn',
      'Tăng cổ tức vì q cao',
    ],
    answer: 1,
    explanation: "q = Giá thị trường DN / Chi phí thay thế vốn. q=0.7 < 1: mua DN trên thị trường (0.7 đồng) rẻ hơn xây mới (1 đồng) → không có động cơ đầu tư mới → I↓. q>1: đầu tư mới có lợi.",
  },
  {
    id: 33, chapter: 'C26',
    text: '"Financial Accelerator" (Bernanke-Gertler) mô tả cơ chế nào?',
    options: [
      'CSTT mở rộng luôn khuếch đại tác động lên GDP',
      'Khi tài sản DN giảm giá → net worth↓ → adverse selection↑ → tín dụng siết → I↓ → Y↓ → tài sản tiếp tục giảm (vòng xoáy tự khuếch đại)',
      'NHTW khuếch đại tín hiệu OMO qua hệ thống ngân hàng',
      'Lạm phát tăng tốc theo cấp số nhân',
    ],
    answer: 1,
    explanation: 'Financial Accelerator: cú sốc ban đầu → net worth DN↓ → adverse selection↑, moral hazard↑ → NH siết tín dụng → I↓ → Y↓ → giá TS tiếp tục↓ → net worth↓ thêm... Vòng xoáy tự khuếch đại. Giải thích tại sao suy thoái sau khủng hoảng tài chính sâu và kéo dài hơn.',
  },
  {
    id: 34, chapter: 'C26',
    text: 'Tại sao CSTT mở rộng có thể KHÔNG HIỆU QUẢ khi lãi suất = 0% (Zero Lower Bound)?',
    options: [
      'Fed không thể mua thêm trái phiếu',
      'Kênh lãi suất bị tắc (i không thể âm) → không khuyến khích thêm đầu tư; NH giữ ER thay vì cho vay',
      'CSTT mở rộng luôn gây lạm phát quá cao',
      'Số nhân tiền âm khi i = 0',
    ],
    answer: 1,
    explanation: 'ZLB: i không thể giảm dưới 0 → Kênh lãi suất truyền thống bị tắc. Thêm: NH giữ ER lớn (e↑) → m↓ → dù MB↑ nhiều, M tăng ít. Giải pháp: QE (kênh giá tài sản), Forward Guidance (kênh kỳ vọng), kênh tỷ giá.',
  },
  {
    id: 35, chapter: 'C26',
    text: 'Kênh nào trong CSTT được kích hoạt NGAY KHI THÔNG BÁO, trước khi thực thi?',
    options: [
      'Kênh lãi suất',
      'Kênh tín dụng ngân hàng',
      'Kênh kỳ vọng (expectations channel)',
      'Kênh balance sheet',
    ],
    answer: 2,
    explanation: 'Kênh kỳ vọng: thị trường phản ứng ngay khi Fed thông báo. Giá CK, tỷ giá, lãi suất dài hạn điều chỉnh ngay dựa trên kỳ vọng về CSTT tương lai. Forward Guidance hoạt động hoàn toàn qua kênh này.',
  },

  // ── TỔNG HỢP ─────────────────────────────────────────────────────────────
  {
    id: 36, chapter: 'C16',
    text: 'Fed mua OMO → NBR↑ → Rs dịch phải → iff ______. Đây là CSTT ______.',
    options: ['↑; thắt chặt', '↓; thắt chặt', '↓; mở rộng', '↑; mở rộng'],
    answer: 2,
    explanation: '✅ Đúng (C): Chuỗi nhân quả OMO mua: Fed mua trái phiếu → trả tiền bằng cách tăng dự trữ ngân hàng → NBR tăng → Rs (cung dự trữ) dịch PHẢI → tại cùng mức cầu Rd, điểm cân bằng mới có iff thấp hơn → chi phí vay liên ngân hàng rẻ hơn → ngân hàng cho vay nhiều hơn → M tăng → đây là CSTT MỞ RỘNG (expansionary). 💡 Nhớ nhanh chiều dịch chuyển: OMO mua → Rs phải → iff giảm (mở rộng). OMO bán → Rs trái → iff tăng (thắt chặt). ❌ A: iff giảm (không tăng) khi OMO mua. ❌ B: iff giảm → CSTT mở rộng, không phải thắt chặt. ❌ D: iff tăng + mở rộng là mâu thuẫn — iff giảm mới là mở rộng.',
  },
  {
    id: 37, chapter: 'C15',
    text: 'Fed thực hiện OMO mua $100 tỷ. Loại dự trữ nào thay đổi?',
    options: [
      'Dự trữ bắt buộc (RR) tăng $100 tỷ',
      'Dự trữ không vay (NBR) tăng $100 tỷ',
      'Dự trữ vay (BR) tăng $100 tỷ',
      'Tổng dự trữ không đổi',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Cần phân biệt 2 loại dự trữ: NBR (Non-Borrowed Reserves / Dự trữ không vay) = dự trữ ngân hàng tạo ra từ OMO và các nguồn khác không phải vay Fed. BR (Borrowed Reserves) = dự trữ ngân hàng có được bằng cách vay từ Fed qua discount window. Khi Fed thực hiện OMO mua: Fed mua trái phiếu CP từ ngân hàng → trả tiền bằng cách ghi tăng tài khoản dự trữ của ngân hàng tại Fed → đây là NBR tăng 100 tỷ. MB = NBR + BR + C. OMO chỉ tác động đến NBR, không ảnh hưởng BR (BR chỉ thay đổi khi ngân hàng chủ động vay/trả Fed). 💡 OMO là công cụ CSTT chủ lực vì Fed kiểm soát hoàn toàn — không phụ thuộc vào quyết định vay của ngân hàng. ❌ A: RR thay đổi khi tiền gửi thay đổi, không trực tiếp từ OMO. ❌ C: BR chỉ thay đổi qua discount window.',
  },
  {
    id: 38, chapter: 'C17',
    text: 'Một NHTW cam kết mục tiêu lạm phát 2% nhưng sau đó mở rộng tiền tệ để hạ thất nghiệp. Đây là ví dụ về:',
    options: [
      'Chính sách phản chu kỳ hợp lý',
      'Time-inconsistency — phá vỡ cam kết vì lợi ích ngắn hạn',
      'Lạm phát mục tiêu thành công',
      'Dual mandate hoạt động hiệu quả',
    ],
    answer: 1,
    explanation: 'Time-inconsistency điển hình: hứa LP=2% → kỳ vọng thấp → "lén" mở rộng tiền tệ vì muốn Y↑ ngắn hạn → LP tăng → mất uy tín. Đây là lý do NHTW cần độc lập và neo danh nghĩa ràng buộc.',
  },
  {
    id: 39, chapter: 'C26',
    text: 'Tại sao giảm phát (deflation) nguy hiểm hơn lạm phát vừa phải?',
    options: [
      'Giảm phát làm tăng xuất khẩu',
      'Giảm phát: r_thực tăng (r=i−π^e, π^e<0) → I↓; nợ thực tăng → NW↓; kỳ vọng tự củng cố → AD↓; ZLB → CSTT mất tác dụng',
      'Giảm phát chỉ ảnh hưởng người tiêu dùng, không ảnh hưởng DN',
      'Giảm phát làm tăng MB',
    ],
    answer: 1,
    explanation: '4 cơ chế giảm phát nguy hiểm: (1) r_thực↑ → I↓; (2) Gánh nặng nợ thực tăng → NW↓ → tín dụng co (Debt deflation — Fisher 1933); (3) Kỳ vọng giảm phát → hoãn tiêu dùng → tự củng cố; (4) ZLB: i không thể âm → CSTT truyền thống bất lực.',
  },
  {
    id: 40, chapter: 'C18',
    text: 'NHNN Việt Nam mua USD bằng VND (không vô hiệu hóa). Tác động lên VND và M2 VND:',
    options: [
      'VND tăng giá; M2 giảm',
      'VND mất giá; M2 tăng (MB VND tăng → M tăng)',
      'VND không đổi; M2 tăng',
      'VND mất giá; M2 không đổi',
    ],
    answer: 1,
    explanation: 'NHNN mua USD = bán VND → cung VND tăng → VND mất giá. Không vô hiệu hóa → MB VND tăng → M2 tăng. Tác động phụ: lạm phát có thể tăng. Đây là lý do NHNN thường kèm vô hiệu hóa khi can thiệp để kiểm soát M2.',
  },

  // ── ĐỀ THI KHOÁ TRƯỚC ──────────────────────────────────────────────────
  {
    id: 41, chapter: 'C2',
    text: 'Tiền có những chức năng cơ bản nào?',
    options: [
      'Phương tiện trao đổi, thước đo giá trị, phương tiện cất trữ giá trị',
      'Phương tiện thanh toán, phương tiện trao đổi',
      'Thước đo giá trị và phương tiện thanh toán',
      'Phương tiện cất trữ giá trị và phương tiện trao đổi',
    ],
    answer: 0,
    explanation: '✅ Đúng (A): Tiền có 3 chức năng cơ bản theo kinh tế học: (1) Phương tiện trao đổi (medium of exchange) — chức năng quan trọng nhất, giải quyết vấn đề "double coincidence of wants" của kinh tế barter (trao đổi hiện vật cần cả hai bên đều muốn thứ kia có). (2) Thước đo giá trị / đơn vị tính toán (unit of account) — định giá mọi hàng hóa/dịch vụ bằng một đơn vị chung, giúp so sánh giá trị dễ dàng. (3) Phương tiện cất trữ giá trị (store of value) — lưu giữ sức mua theo thời gian (dù không hoàn hảo vì lạm phát). 💡 "Phương tiện thanh toán" không phải chức năng riêng biệt — nó là hệ quả của chức năng trao đổi. ❌ B, C, D: đều thiếu đủ 3 chức năng chuẩn.',
  },
  {
    id: 42, chapter: 'C2',
    text: 'Yếu tố nào sau đây KHÔNG phải là thành phần của cung tiền M1?',
    options: [
      'Tiền mặt lưu hành',
      'Tiền gửi không kỳ hạn',
      'Tiền gửi tiết kiệm',
      'Séc du lịch',
    ],
    answer: 2,
    explanation: '✅ Đúng (C — tiền gửi tiết kiệm KHÔNG thuộc M1): M1 (cung tiền hẹp) = Tiền mặt lưu hành ngoài ngân hàng + Tiền gửi không kỳ hạn (demand deposits/checking accounts) + Séc du lịch. M2 (cung tiền rộng) = M1 + Tiền gửi tiết kiệm (savings deposits) + Tiền gửi có kỳ hạn nhỏ (small CDs) + Money market mutual funds. 💡 Logic phân loại: M1 là tiền có tính thanh khoản cao nhất — dùng được ngay lập tức không cần chờ. Tiền gửi tiết kiệm có giới hạn rút tiền hoặc cần thông báo trước → kém thanh khoản hơn → chỉ nằm trong M2. Nhớ: M1 ⊂ M2, mọi thứ trong M1 đều thuộc M2 nhưng không chiều ngược lại.',
  },
  {
    id: 43, chapter: 'C17',
    text: 'Ngân hàng trung ương thực hiện chính sách tiền tệ nhằm mục tiêu:',
    options: [
      'Ổn định giá cả',
      'Tăng trưởng kinh tế',
      'Giảm thất nghiệp',
      'Tất cả các đáp án trên',
    ],
    answer: 3,
    explanation: 'NHTW thường theo đuổi đồng thời nhiều mục tiêu: ổn định giá cả (kiểm soát lạm phát), tăng trưởng kinh tế bền vững, và giảm thất nghiệp. Fed (Mỹ) có "dual mandate" — ổn định giá + việc làm tối đa. ECB ưu tiên ổn định giá (hierarchical mandate). Các NHTW còn theo đuổi ổn định tài chính, tỷ giá.',
  },
  {
    id: 44, chapter: 'C16',
    text: 'Công cụ quan trọng nhất của chính sách tiền tệ là:',
    options: [
      'Dự trữ bắt buộc',
      'Hoạt động thị trường mở (OMO)',
      'Lãi suất tái chiết khấu',
      'Hạn mức tín dụng',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Trong bộ 3 công cụ CSTT (OMO, discount rate, RR), OMO được xem là công cụ trung tâm và quan trọng nhất vì 4 ưu điểm vượt trội: Linh hoạt — thực hiện được hàng ngày, quy mô tùy chỉnh từ nhỏ đến rất lớn. Dễ đảo ngược — sai có thể sửa ngay trong ngày tiếp theo. Kiểm soát hoàn toàn — Fed chủ động, không phụ thuộc hành vi ngân hàng. Tác động trực tiếp và nhanh — tức thì lên dự trữ và iff. 💡 Thực tế: Ủy ban FOMC họp 8 lần/năm để quyết định mục tiêu iff, sau đó bàn giao cho New York Fed thực hiện OMO hàng ngày để duy trì iff gần mục tiêu. ❌ A: RR ít dùng vì cứng nhắc, tác động quá mạnh. ❌ C: Lãi suất tái chiết khấu là công cụ thụ động — phụ thuộc ngân hàng có muốn vay hay không.',
  },
  {
    id: 45, chapter: 'C15',
    text: 'Số nhân tiền tệ phụ thuộc vào:',
    options: [
      'Tỷ lệ dự trữ bắt buộc (rr)',
      'Tỷ lệ tiền mặt / tiền gửi (c)',
      'Dự trữ vượt mức (e)',
      'Tất cả các yếu tố trên',
    ],
    answer: 3,
    explanation: '✅ Đúng (D): Công thức đầy đủ: m = (1+c)/(rr+e+c). Cả 3 yếu tố đều ảnh hưởng NGHỊCH CHIỀU đến m: rr↑ → mẫu số tăng → m↓ (Fed kiểm soát). e↑ → mẫu số tăng → m↓ (ngân hàng TM quyết định — giữ nhiều dự trữ vượt mức hơn). c↑ → tử số tăng nhẹ nhưng mẫu số tăng nhiều hơn → m↓ (công chúng quyết định — giữ nhiều tiền mặt hơn). 💡 Vì m phụ thuộc vào hành vi của cả 3 bên, Fed chỉ kiểm soát trực tiếp MB chứ không kiểm soát hoàn toàn M = m × MB. Điều này giải thích tại sao CSTT đôi khi "mất tác dụng" — ví dụ Fed bơm MB mạnh nhưng ngân hàng tích trữ ER (e↑) hoặc dân rút tiền mặt (c↑) → m giảm → M không tăng như kỳ vọng.',
  },
  {
    id: 46, chapter: 'C15',
    text: 'Trong hệ thống ngân hàng, việc tạo tiền xảy ra khi:',
    options: [
      'Ngân hàng nhận tiền gửi',
      'Ngân hàng cho vay',
      'Ngân hàng trung ương phát hành tiền',
      'Chính phủ chi tiêu',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Quá trình tạo tiền (money creation) xảy ra khi ngân hàng cho vay, không phải khi nhận tiền gửi. Ví dụ với rr=10%: NH A nhận tiền gửi 1,000 → giữ 100 dự trữ bắt buộc → cho vay 900. Người vay 900 gửi vào NH B → NH B giữ 90 → cho vay 810. NH C nhận 810 → cho vay 729... Tổng tiền gửi tạo ra = 1,000 × (1/0.1) = 10,000. Tổng tiền mới tạo = 9,000. 💡 Cơ chế cốt lõi: mỗi đồng cho vay trở thành tiền gửi ở ngân hàng khác, rồi lại được cho vay tiếp — đây là "fractional reserve banking" (ngân hàng dự trữ một phần). ❌ A: Nhận tiền gửi chỉ là bước đầu — chưa tạo tiền mới. ❌ C: NHTW phát hành tiền là tạo MB (tiền cơ sở), không phải M (cung tiền rộng). ❌ D: Chi tiêu chính phủ tác động gián tiếp qua MB.',
  },
  {
    id: 47, chapter: 'C16',
    text: 'Nếu ngân hàng trung ương MUA trái phiếu trên thị trường mở thì:',
    options: [
      'Cung tiền giảm',
      'Cung tiền tăng',
      'Lãi suất tăng',
      'Dự trữ ngân hàng giảm',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): NHTW mua trái phiếu trên thị trường mở là OMO mở rộng (expansionary OMO). Cơ chế: NHTW trả tiền cho người bán (primary dealer) bằng cách ghi tăng tài khoản dự trữ của ngân hàng tại NHTW → R (dự trữ) tăng → Rs dịch phải → i_ff giảm → chi phí vốn rẻ hơn → ngân hàng cho vay nhiều hơn → qua số nhân tiền, M tăng bội số. 💡 Đây là phản xạ cốt lõi cần nhớ: NHTW mua = bơm tiền = M tăng = lãi suất giảm = kích thích kinh tế. NHTW bán = hút tiền = M giảm = lãi suất tăng = thắt chặt kinh tế. ❌ A: Cung tiền tăng (không giảm) khi NHTW mua. ❌ C: Lãi suất giảm (không tăng). ❌ D: Dự trữ ngân hàng tăng (không giảm).',
  },
  {
    id: 48, chapter: 'C15',
    text: 'Nếu tỷ lệ dự trữ bắt buộc TĂNG, thì:',
    options: [
      'Số nhân tiền tăng',
      'Số nhân tiền giảm',
      'Cung tiền tăng',
      'Không ảnh hưởng',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Cơ chế: rr↑ → mẫu số trong m = (1+c)/(rr+e+c) tăng → m giảm → M = m × MB giảm (MB giữ nguyên). Ví dụ số: rr từ 10%→20%, c=0.2, e=0: m trước = (1.2)/(0.1+0+0.2) = 1.2/0.3 = 4. m sau = (1.2)/(0.2+0+0.2) = 1.2/0.4 = 3. Cung tiền giảm 25%. 💡 Tại sao tăng DTBB ít được dùng dù hiệu lực mạnh? (1) Thay đổi đột ngột gây sốc cho ngân hàng — buộc họ thu hẹp cho vay gấp. (2) Ngân hàng phải tái cơ cấu danh mục tài sản ngay lập tức, gây bất ổn. (3) Thiếu linh hoạt — không thể tinh chỉnh từng bước nhỏ như OMO. Fed Mỹ hầu như không thay đổi rr từ 1992 đến 2020. ❌ A & C: rr↑ làm giảm số nhân và giảm cung tiền, không phải tăng.',
  },
  {
    id: 49, chapter: 'C17',
    text: 'Lạm phát là:',
    options: [
      'Sự tăng liên tục của mức giá chung',
      'Sự giảm mức giá',
      'Sự tăng sản lượng',
      'Sự tăng thất nghiệp',
    ],
    answer: 0,
    explanation: 'Lạm phát (inflation) = sự tăng liên tục và bền vững của mức giá chung trong nền kinh tế. Từ khoá quan trọng: "liên tục" (không phải tăng giá một lần) và "mức giá chung" (không phải giá một mặt hàng). Giảm phát (deflation) = mức giá giảm liên tục. Thiểu phát (disinflation) = lạm phát giảm nhưng vẫn dương.',
  },
  {
    id: 50, chapter: 'C17',
    text: 'Chỉ số thường dùng để đo lạm phát là:',
    options: [
      'GDP',
      'CPI',
      'GNP',
      'NNP',
    ],
    answer: 1,
    explanation: 'CPI (Consumer Price Index — Chỉ số giá tiêu dùng) là thước đo lạm phát phổ biến nhất: đo giá của một "rổ" hàng hóa tiêu dùng cố định. Ngoài CPI còn có PCE deflator (Fed ưa dùng) và GDP deflator. GDP đo sản lượng, GNP/NNP là các chỉ số thu nhập quốc dân.',
  },
  {
    id: 51, chapter: 'C17',
    text: 'Theo đường Phillips, trong ngắn hạn có mối quan hệ:',
    options: [
      'Thuận chiều giữa lạm phát và thất nghiệp',
      'Nghịch chiều giữa lạm phát và thất nghiệp',
      'Không có mối quan hệ',
      'Phụ thuộc vào lãi suất',
    ],
    answer: 1,
    explanation: 'Đường Phillips ngắn hạn: quan hệ nghịch chiều giữa lạm phát (π) và thất nghiệp (u) — khi nền kinh tế mở rộng, thất nghiệp giảm nhưng lạm phát tăng. Tuy nhiên trong dài hạn, đường Phillips thẳng đứng tại tỷ lệ thất nghiệp tự nhiên (NAIRU) — không có sự đánh đổi dài hạn.',
  },
  {
    id: 52, chapter: 'C17',
    text: 'Chính sách tiền tệ THẮT CHẶT nhằm mục tiêu:',
    options: [
      'Giảm lạm phát',
      'Tăng lạm phát',
      'Tăng cung tiền',
      'Tăng chi tiêu chính phủ',
    ],
    answer: 0,
    explanation: 'CSTT thắt chặt (contractionary monetary policy): giảm M → tăng i → giảm I và C → giảm AD → giảm áp lực lạm phát. Công cụ: bán TP (OMO), tăng rr, tăng i_d. Ví dụ: Fed tăng mạnh lãi suất 2022–2023 để kiềm lạm phát từ 9% xuống còn ~3%.',
  },
  {
    id: 53, chapter: 'C16',
    text: 'Nếu ngân hàng trung ương BÁN trái phiếu trên thị trường mở:',
    options: [
      'Cung tiền tăng',
      'Cung tiền giảm',
      'Lãi suất giảm',
      'Đầu tư tăng',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): NHTW bán trái phiếu là OMO thắt chặt (contractionary OMO) — đối xứng hoàn toàn với mua. Cơ chế: dealer mua trái phiếu → thanh toán bằng cách chuyển tiền cho NHTW → dự trữ ngân hàng tại NHTW giảm → R↓ → Rs dịch TRÁI → i_ff↑ → chi phí vay liên ngân hàng tăng → ngân hàng thắt chặt cho vay → M giảm → lãi suất thị trường tăng → đầu tư giảm → GDP giảm (kìm lạm phát). 💡 Quy tắc đối xứng: Mua TP → M↑, i↓, kích thích kinh tế. Bán TP → M↓, i↑, thắt chặt kinh tế (chống lạm phát). ❌ A: Cung tiền giảm, không tăng. ❌ C: Lãi suất tăng, không giảm. ❌ D: Đầu tư giảm (chi phí vốn cao hơn), không tăng.',
  },
  {
    id: 54, chapter: 'C15',
    text: 'Cung tiền M2 bao gồm:',
    options: [
      'M1 + tiền gửi tiết kiệm + CDs nhỏ',
      'Chỉ tiền mặt',
      'Chỉ tiền gửi',
      'Chỉ tiền gửi có kỳ hạn',
    ],
    answer: 0,
    explanation: '✅ Đúng (A): Phân cấp cung tiền theo tính thanh khoản giảm dần: M1 (hẹp nhất) = Tiền mặt lưu hành + Tiền gửi không kỳ hạn (checking/demand deposits) + Séc du lịch. M2 (rộng hơn) = M1 + Tiền gửi tiết kiệm (savings deposits) + CDs nhỏ dưới 100k (small time deposits) + Tiền gửi thị trường tiền tệ (money market deposit accounts). M3 (ở một số nước) = M2 + CDs lớn + repo + eurodollar... 💡 Logic phân loại: tiêu chí là tính thanh khoản — dùng được ngay không mất giá trị. M1 dùng được ngay; M2 có thể cần thời gian hoặc chịu phạt khi rút sớm. Fed theo dõi M2 là thước đo cung tiền chính trong thực tế CSTT. ❌ B, C, D: đều mô tả không đầy đủ — bỏ qua M1 là thành phần cơ sở của M2.',
  },
  {
    id: 55, chapter: 'C15',
    text: 'Theo lý thuyết số lượng tiền tệ MV = PY, V là:',
    options: [
      'Thu nhập quốc dân',
      'Tốc độ lưu chuyển tiền',
      'Cung tiền',
      'Mức giá',
    ],
    answer: 1,
    explanation: '✅ Đúng (B): Phương trình trao đổi (Equation of Exchange) của Irving Fisher: MV = PY. M = cung tiền (money supply). V = velocity of money — tốc độ lưu chuyển tiền, tức số lần trung bình một đồng tiền được dùng để mua hàng hóa/dịch vụ trong một năm. P = mức giá chung (price level). Y = sản lượng thực (real output/GDP thực). PY = GDP danh nghĩa (nominal GDP). 💡 Từ đây suy ra Thuyết số lượng tiền (Quantity Theory of Money): nếu V ổn định (giả định của các nhà tiền tệ học — monetarists) và Y tăng theo tiềm năng, thì M↑ → P↑ tỉ lệ thuận → lạm phát. Friedman: "Inflation is always and everywhere a monetary phenomenon." ❌ A: Y là sản lượng thực. ❌ C: M là cung tiền. ❌ D: P là mức giá.',
  },
  {
    id: 56, chapter: 'C15',
    text: 'Nếu tốc độ lưu chuyển tiền (V) TĂNG, khi các yếu tố khác không đổi:',
    options: [
      'GDP danh nghĩa (PY) tăng',
      'GDP danh nghĩa giảm',
      'Mức giá giảm',
      'Cung tiền giảm',
    ],
    answer: 0,
    explanation: '✅ Đúng (A): Từ MV = PY: nếu M cố định mà V tăng → tích PY phải tăng để phương trình cân bằng → GDP danh nghĩa (PY) tăng. GDP danh nghĩa tăng có thể phản ánh: P↑ (lạm phát) hoặc Y↑ (tăng trưởng thực) hoặc cả hai. V tăng có nghĩa là mỗi đồng tiền đổi tay nhiều lần hơn trong năm — xảy ra khi: kỳ vọng lạm phát cao (người ta tiêu nhanh trước khi tiền mất giá), niềm tin kinh tế cải thiện, công nghệ thanh toán nhanh hơn. 💡 Ý nghĩa chính sách: nếu V không ổn định (biến động mạnh như khủng hoảng 2008), thì dù Fed kiểm soát M, PY vẫn dao động khó đoán — đây là một trong những lý do targeting M2 không còn được dùng nhiều. ❌ B: V↑ thì PY phải tăng, không giảm. ❌ C & D: Mức giá và cung tiền không giảm từ điều kiện đã cho.',
  },
  {
    id: 57, chapter: 'C16',
    text: 'Chính sách tiền tệ MỞ RỘNG sẽ:',
    options: [
      'Tăng cung tiền',
      'Giảm lãi suất',
      'Kích thích đầu tư',
      'Tất cả các đáp án trên',
    ],
    answer: 3,
    explanation: '✅ Đúng (D): CSTT mở rộng kích hoạt một chuỗi phản ứng theo nhiều kênh — tất cả A, B, C đều đúng. Kênh lãi suất (chính): M↑ → i↓ → chi phí vốn giảm → I↑ → AD↑ → Y↑. Kênh tỷ giá: M↑ → i↓ → vốn chảy ra nước ngoài → nội tệ mất giá → xuất khẩu rẻ hơn → NX↑ → Y↑. Kênh giá tài sản: M↑ → i↓ → giá cổ phiếu, bất động sản tăng → của cải tăng → tiêu dùng tăng (wealth effect); Tobin q tăng → đầu tư tăng. Kênh tín dụng: M↑ → ngân hàng có nhiều dự trữ → cho vay dễ hơn → bank lending channel. 💡 Vì vậy: tăng cung tiền (A) + giảm lãi suất (B) + kích thích đầu tư (C) đều là hệ quả đúng của CSTT mở rộng → đáp án là Tất cả (D).',
  },
  {
    id: 58, chapter: 'C17',
    text: 'Neo danh nghĩa (nominal anchor) giúp ổn định giá bằng cách:',
    options: [
      'Tăng chi tiêu chính phủ',
      'Giữ kỳ vọng lạm phát ở mức thấp',
      'Tăng thuế',
      'Giảm thất nghiệp',
    ],
    answer: 1,
    explanation: 'Neo danh nghĩa (tỷ giá cố định, mục tiêu M, mục tiêu lạm phát) neo kỳ vọng lạm phát của dân chúng và thị trường. Khi kỳ vọng lạm phát thấp → tiền lương và giá được đàm phán ở mức thấp → lạm phát thực tế thấp (self-fulfilling). Đây là cơ chế "commitment device" giải quyết bài toán time-inconsistency.',
  },
  {
    id: 59, chapter: 'C26',
    text: 'Nếu các yếu tố khác không đổi, tăng chi tiêu chính phủ sẽ:',
    options: [
      'Giảm tổng cầu (AD)',
      'Không ảnh hưởng tổng cầu',
      'Tăng tổng cầu (AD)',
      'Giảm đầu tư',
    ],
    answer: 2,
    explanation: 'AD = C + I + G + NX. Tăng G trực tiếp làm AD↑ (dịch đường AD sang phải). Đây là chính sách tài khoá mở rộng. Lưu ý hiệu ứng "crowding out": G↑ → cần vay nhiều hơn → i↑ → I↓ (một phần). Nhưng nếu các yếu tố khác không đổi (đề bài giả định), tác động ròng là AD↑.',
  },
  {
    id: 60, chapter: 'C15',
    text: 'Nếu tỷ lệ dự trữ bắt buộc GIẢM, thì:',
    options: [
      'Cung tiền tăng',
      'Cung tiền giảm',
      'Số nhân tiền giảm',
      'Không ảnh hưởng',
    ],
    answer: 0,
    explanation: '✅ Đúng (A): Cơ chế đối xứng với câu Q48: rr↓ → mẫu số trong m = (1+c)/(rr+e+c) giảm → m tăng → M = m × MB tăng (MB không đổi). Ví dụ số: rr từ 10%→5%, c=0.2, e=0: m trước = 1.2/(0.1+0+0.2) = 1.2/0.3 = 4. m sau = 1.2/(0.05+0+0.2) = 1.2/0.25 = 4.8. Cung tiền tăng 20%. 💡 Cơ chế truyền dẫn: rr↓ → ngân hàng được phép giữ ít dự trữ hơn → cho vay nhiều hơn trên cùng lượng tiền gửi → quá trình nhân tiền diễn ra mạnh hơn → M tăng → lãi suất giảm → đầu tư và tiêu dùng tăng → kích thích kinh tế. Thực tế: Fed dùng công cụ này rất thận trọng — tháng 3/2020 Fed hạ rr xuống 0% để hỗ trợ kinh tế COVID. ❌ B & C: rr↓ làm tăng số nhân và tăng cung tiền, không phải ngược lại.',
  },
];
